### ISSUE TITLE
Electricity consumption of hydrogen liquefaction only includes electrolysis

### ISSUE THREAD

**Issue by iancostalves** [AeroMAPS/AeroMAPS#70]
How it is computed in file `aeromaps.models.impacts.energy_resources.resources_consumption` :

> electricity_hydrogen_consumption = (
            hydrogen_electrolysis_share
            / 100
            * energy_consumption_hydrogen
            / 10**12
            / electrolysis_efficiency
            / liquefaction_efficiency
        )

It includes the lost energy during electrolysis and liquefaction, but there is still a part of gas-hydrogen produced (gas, gas w/ CCS, coal, coal w/ CCS) that needs to be liquified ...

A possible way to fix it is to separate electricity consumption from hydrogen into two terms : 
One for electrolysis and liquefaction alone, same as before
> electricity_hydrogen_electrolysis_consumption = (
            hydrogen_electrolysis_share
            / 100
            * energy_consumption_hydrogen
            / 10**12
            / electrolysis_efficiency
            / liquefaction_efficiency
        )

And another to include liquefaction of non-electrolysis hydrogen production

> electricity_hydrogen_non_electrolysis_consumption = (
            (1 - hydrogen_electrolysis_share)
            / 100
            * energy_consumption_hydrogen
            / 10**12
            / liquefaction_efficiency
        )

**Comment by iancostalves** [comment]
The emission factor of hydrogen production also seems to be affected by this problem...

How it is computed in `aeromaps.models.air_transport.aircraft_energy.fuel_emissions` :


        hydrogen_electrolysis_emission_factor = (
            electricity_emission_factor / 3.6 / electrolysis_efficiency / liquefaction_efficiency
        )

        hydrogen_mean_emission_factor = (
            hydrogen_electrolysis_emission_factor * hydrogen_electrolysis_share / 100
            + hydrogen_gas_ccs_emission_factor * hydrogen_gas_ccs_share / 100
            + hydrogen_coal_ccs_emission_factor * hydrogen_coal_ccs_share / 100
            + hydrogen_gas_emission_factor * hydrogen_gas_share / 100
            + hydrogen_coal_emission_factor * hydrogen_coal_share / 100
        )


To avoid this, we may exclude liquefaction from the hydrogen electrolysis and add it to overal hydrogen emission factor :


        hydrogen_electrolysis_emission_factor = (
            electricity_emission_factor / 3.6 / electrolysis_efficiency
        )

        hydrogen_mean_emission_factor = (
            hydrogen_electrolysis_emission_factor * hydrogen_electrolysis_share / 100
            + hydrogen_gas_ccs_emission_factor * hydrogen_gas_ccs_share / 100
            + hydrogen_coal_ccs_emission_factor * hydrogen_coal_ccs_share / 100
            + hydrogen_gas_emission_factor * hydrogen_gas_share / 100
            + hydrogen_coal_emission_factor * hydrogen_coal_share / 100
        )  / liquefaction_efficiency

**Comment by thomasplanes** [comment]
Thank you for detecting the bug. Solving the problem actually required a more detailed modification than the one proposed. A clear distinction between liquid and gaseous hydrogen has been made. The correction of this issue will be included in an upcoming PR including marginal abatement cost models.
